### ISSUE TITLE
Crash because of call to non-existing function: require(...).on

### ISSUE THREAD

**Issue by gramosg** [paulmillr/native-notifier#8]
Commit [e7887fc](https://github.com/paulmillr/native-notifier/commit/e7887fcfbedd8896f9ae4a8ed3142649509db90c) introduces a runtime crash in line 3:

> TypeError: require(...).on is not a function

Can be reproduced directly from [NPM](https://www.npmjs.com/package/native-notifier) by clicking in "Test with RunKit".

**Comment by HQJacques** [comment]
Seeing the same issue:

`$ npm run deploy

> @ deploy xxx_project_xxx/assets
> brunch build --production

Brunch: Local install exists, but failed to load it. Continuing with global install: TypeError: require(...).on is not a function
    at loadE (xxx_project_xxx/assets/node_modules/native-notifier/index.js:3:49)
    at module.exports (xxx_project_xxx/assets/node_modules/native-notifier/index.js:7:27)
    at Object.<anonymous> (xxx_project_xxx/assets/node_modules/native-notifier/index.js:13:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
xxx_project_xxx/assets/node_modules/native-notifier/index.js:3
const loadE = moduleName => require(moduleName).on('error', () => {});
                                                ^

TypeError: require(...).on is not a function
    at loadE (xxx_project_xxx/assets/node_modules/native-notifier/index.js:3:49)
    at module.exports (xxx_project_xxx/assets/node_modules/native-notifier/index.js:7:27)
    at Object.<anonymous> (xxx_project_xxx/assets/node_modules/native-notifier/index.js:13:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)`

package.json
`{
  "repository": {},
  "license": "MIT",
  "scripts": {
    "deploy": "brunch build --production",
    "watch": "brunch watch --stdin"
  },
  "dependencies": {
    "bootstrap": "^4.1.3",
    "jquery": "^3.3.1",
    "phoenix": "file:../deps/phoenix",
    "phoenix_html": "file:../deps/phoenix_html",
    "popper.js": "^1.14.4"
  },
  "devDependencies": {
    "babel-brunch": "^7.0.0",
    "babel-preset-env": "^1.7.0",
    "brunch": "^2.10.17",
    "clean-css-brunch": "2.10.0",
    "copycat-brunch": "^1.1.0",
    "sass-brunch": "^2.10.7",
    "uglify-js-brunch": "2.10.0"
  }
}
`

**Comment by HQJacques** [comment]
After hard-coding the `devDependencies` to `"native-notifier": "0.1.1",` I can build releases again.

**Comment by HQJacques** [comment]
@replicat0r Pinning the dependency (from my previous comment) allowed my (phoenix also) builds to complete.

**Comment by diogo-ribeiro-bitmaker** [comment]
same here...

**Comment by the-mikedavis** [comment]
By removing said function, my brunch build succeeds (linux):

```js
'use strict';
const os = require('os').platform();
const loadE = moduleName => require(moduleName);// .on('error', () => {}); remove this, or just use plain `require` below

module.exports = (() => {
  switch (os) {
    case 'darwin': return loadE('./macos');
    case 'linux': return loadE('./linux');
    case 'win32': return loadE('./windows');
  }

  return () => {};
})();
```

**Comment by replicat0r** [comment]
@HQJacques are you talking about modifiying the package.json inside the node_module of phx asset folder? Its def a quick fix, but it breaks Brunch anytime you make a new project, and breaks global Brunch install

**Comment by ancient-alchemist** [comment]
I was running into this same problem. My solution was to upgrade node to latest version (8.x). I broke my prod server because of this :rage: :cry:

**Comment by paulmillr** [comment]
Sorry for that folks — should be fine now.

**Comment by paulmedynski** [comment]
My bad too - I never thought to pull master and try it first.  I figured it was already working and just waiting for a release.
